variables:
  CI_IMAGE: $DOCKER_HUB_USER/nuttssh

before_script:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use

build-master:
  image: $DOCKER_HUB_USER/docker:buildx
  stage: build
  services:
    - name: docker:dind
  script:
    - >-
      docker buildx build --push -t "$CI_IMAGE"
      --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 .
  only:
    - master

build-feature:
  image: $DOCKER_HUB_USER/docker:buildx
  stage: build
  services:
    - docker:dind
  variables:
    PLATFORM: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
  script:
    - docker buildx build --push -t "$CI_IMAGE:$CI_COMMIT_REF_SLUG" 
      --platform "$PLATFORM" --cache-from "$CI_IMAGE:$CI_COMMIT_REF_SLUG" .
  except:
    - master
