before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use
  - docker buildx ls

build-master:
  image: oofnik/docker:buildx
  stage: build
  services:
    - name: docker:dind
  script:
    - >-
      docker buildx build --push -t "$CI_REGISTRY_IMAGE"
      --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 .
  only:
    - master

build-feature:
  image: oofnik/docker:buildx
  stage: build
  services:
    - docker:dind
  script:
    - >-
      docker buildx build --push -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 .
  except:
    - master
